/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    'bg-blue-500',
    'text-white',
    'rounded-lg',
    'bg-gray-100',
    'text-gray-900',
    'text-blue-600',
    'text-green-600',
    'text-purple-600',
    'text-yellow-500',
    'text-gray-600',
    'text-gray-700',
    'text-gray-500',
    'bg-white',
    'shadow-sm',
    'border',
    'border-gray-200',
    'hover:bg-blue-700',
    'hover:bg-green-600',
    'hover:bg-red-600',
    'hover:bg-purple-200',
    'hover:bg-yellow-200',
    'hover:bg-gray-200',
    'transition-colors',
    'duration-200',
    'focus:border-blue-500',
    'focus:ring-2',
    'focus:ring-blue-200',
    'placeholder-gray-400',
    'bg-blue-600',
    'bg-green-500',
    'bg-red-500',
    'bg-purple-100',
    'bg-yellow-100',
    'bg-gray-100',
    'text-blue-800',
    'text-green-800',
    'text-red-800',
    'text-purple-800',
    'text-yellow-800',
    'text-gray-800',
    'border-blue-200',
    'border-green-200',
    'border-red-200',
    'border-purple-200',
    'border-yellow-200',
    'border-gray-200',
  ],
  theme: {
    extend: {
      colors: {
        'brand-blue': {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-up': 'slideUp 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
} 