# Production environment (VPS deployment)
# Run with: docker compose -f docker-compose.prod.yml up
services:
  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DUCKDB_PATH: /code/duckdb/washing_machines.duckdb
    volumes: ["duckdb-data:/code/duckdb"]
    expose: ["8000"]
    
  frontend:
    build: ./frontend
    command: npm run start
    depends_on: [backend]
    expose: ["3000"]
    environment:
      NEXT_PUBLIC_API_URL: ""
      
  nginx:
    image: nginx:1.27-alpine
    depends_on: [frontend, backend]
    ports: ["80:80", "443:443"]
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    
volumes:
  duckdb-data:
