services:
  db:
    image: postgres:16
    platform: linux/arm64
    environment:
      POSTGRES_PASSWORD: postgres
    ports: ["5432:5432"]
    volumes: ["db-data:/var/lib/postgresql/data"]
  backend:
    build: ./backend
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on: [db]
    environment: 
      DATABASE_URL: postgres://postgres:postgres@db:5432/postgres
    volumes: ["./backend:/code"]
    ports: ["8000:8000"]
  frontend:
    build: ./frontend
    volumes: ["./frontend:/app"] 
    command: npm run dev
    depends_on: [backend]
    ports: ["3000:3000"]
volumes:
  db-data:

