-- Migration: Create washing_machines table
-- This table stores all washing machine durability data from data.gouv.fr

CREATE TABLE washing_machines (
    id SERIAL PRIMARY KEY,
    
    -- Core identification fields
    id_unique TEXT,
    id_modele TEXT,
    referentiel_id_modele TEXT,
    nom_modele TEXT,
    categorie_produit TEXT,
    id_metteur_sur_le_marche TEXT,
    referentiel_id_metteur_sur_marche TEXT,
    nom_metteur_sur_le_marche TEXT,
    date_calcul DATE,
    url_tableau_detail_notation TEXT,
    
    -- Main scores
    note_id FLOAT,
    note_reparabilite FLOAT,
    note_fiabilite FLOAT,
    
    -- Detailed scores - Category A
    note_A_c1 FLOAT,
    note_A_c2 FLOAT,
    note_A_c3 FLOAT,
    note_A_c4 FLOAT,
    note_A_c1_1 FLOAT,
    note_A_c1_2 FLOAT,
    note_A_c2_1 FLOAT,
    note_A_c2_2 FLOAT,
    note_A_c2_3 FLOAT,
    note_A_c3_1 FLOAT,
    note_A_c3_2 FLOAT,
    note_A_c3_3 FLOAT,
    note_A_c3_4 FLOAT,
    
    -- Detailed scores - Category B
    note_B_c1 FLOAT,
    note_B_c2 FLOAT,
    note_B_c3 FLOAT,
    note_B_c1_1 FLOAT,
    note_B_c1_2 FLOAT,
    note_B_c2_1 FLOAT,
    note_B_c2_2 FLOAT,
    note_B_c3_1 FLOAT,
    note_B_c3_2 FLOAT,
    
    -- Documentation and accessibility
    accessibilite_compteur_usage TEXT,
    lien_documentation_professionnels TEXT,
    lien_documentation_particuliers TEXT,
    
    -- Parts list 2 (5 parts)
    nom_piece_1_liste_2 TEXT,
    etape_demontage_piece_1_liste_2 TEXT,
    nom_piece_2_liste_2 TEXT,
    etape_demontage_piece_2_liste_2 TEXT,
    nom_piece_3_liste_2 TEXT,
    etape_demontage_piece_3_liste_2 TEXT,
    nom_piece_4_liste_2 TEXT,
    etape_demontage_piece_4_liste_2 TEXT,
    nom_piece_5_liste_2 TEXT,
    etape_demontage_piece_5_liste_2 TEXT,
    
    -- Spare parts for repairer (15 parts)
    nom_piece_detachee_1_reparateur TEXT,
    delai_jours_piece_detachee_1_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_1_reparateur INTEGER,
    nom_piece_detachee_2_reparateur TEXT,
    delai_jours_piece_detachee_2_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_2_reparateur INTEGER,
    nom_piece_detachee_3_reparateur TEXT,
    delai_jours_piece_detachee_3_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_3_reparateur INTEGER,
    nom_piece_detachee_4_reparateur TEXT,
    delai_jours_piece_detachee_4_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_4_reparateur INTEGER,
    nom_piece_detachee_5_reparateur TEXT,
    delai_jours_piece_detachee_5_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_5_reparateur INTEGER,
    nom_piece_detachee_6_reparateur TEXT,
    delai_jours_piece_detachee_6_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_6_reparateur INTEGER,
    nom_piece_detachee_7_reparateur TEXT,
    delai_jours_piece_detachee_7_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_7_reparateur INTEGER,
    nom_piece_detachee_8_reparateur TEXT,
    delai_jours_piece_detachee_8_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_8_reparateur INTEGER,
    nom_piece_detachee_9_reparateur TEXT,
    delai_jours_piece_detachee_9_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_9_reparateur INTEGER,
    nom_piece_detachee_10_reparateur TEXT,
    delai_jours_piece_detachee_10_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_10_reparateur INTEGER,
    nom_piece_detachee_11_reparateur TEXT,
    delai_jours_piece_detachee_11_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_11_reparateur INTEGER,
    nom_piece_detachee_12_reparateur TEXT,
    delai_jours_piece_detachee_12_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_12_reparateur INTEGER,
    nom_piece_detachee_13_reparateur TEXT,
    delai_jours_piece_detachee_13_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_13_reparateur INTEGER,
    nom_piece_detachee_14_reparateur TEXT,
    delai_jours_piece_detachee_14_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_14_reparateur INTEGER,
    nom_piece_detachee_15_reparateur TEXT,
    delai_jours_piece_detachee_15_reparateur INTEGER,
    nb_annees_disponibilite_piece_detachee_15_reparateur INTEGER,
    
    -- Spare parts for producer (15 parts)
    nom_piece_detachee_1_producteur TEXT,
    delai_jours_piece_detachee_1_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_1_producteur INTEGER,
    nom_piece_detachee_2_producteur TEXT,
    delai_jours_piece_detachee_2_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_2_producteur INTEGER,
    nom_piece_detachee_3_producteur TEXT,
    delai_jours_piece_detachee_3_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_3_producteur INTEGER,
    nom_piece_detachee_4_producteur TEXT,
    delai_jours_piece_detachee_4_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_4_producteur INTEGER,
    nom_piece_detachee_5_producteur TEXT,
    delai_jours_piece_detachee_5_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_5_producteur INTEGER,
    nom_piece_detachee_6_producteur TEXT,
    delai_jours_piece_detachee_6_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_6_producteur INTEGER,
    nom_piece_detachee_7_producteur TEXT,
    delai_jours_piece_detachee_7_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_7_producteur INTEGER,
    nom_piece_detachee_8_producteur TEXT,
    delai_jours_piece_detachee_8_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_8_producteur INTEGER,
    nom_piece_detachee_9_producteur TEXT,
    delai_jours_piece_detachee_9_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_9_producteur INTEGER,
    nom_piece_detachee_10_producteur TEXT,
    delai_jours_piece_detachee_10_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_10_producteur INTEGER,
    nom_piece_detachee_11_producteur TEXT,
    delai_jours_piece_detachee_11_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_11_producteur INTEGER,
    nom_piece_detachee_12_producteur TEXT,
    delai_jours_piece_detachee_12_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_12_producteur INTEGER,
    nom_piece_detachee_13_producteur TEXT,
    delai_jours_piece_detachee_13_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_13_producteur INTEGER,
    nom_piece_detachee_14_producteur TEXT,
    delai_jours_piece_detachee_14_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_14_producteur INTEGER,
    nom_piece_detachee_15_producteur TEXT,
    delai_jours_piece_detachee_15_producteur INTEGER,
    nb_annees_disponibilite_piece_detachee_15_producteur INTEGER,
    
    -- Spare parts for distributor (15 parts)
    nom_piece_detachee_1_distributeur TEXT,
    delai_jours_piece_detachee_1_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_1_distributeur INTEGER,
    nom_piece_detachee_2_distributeur TEXT,
    delai_jours_piece_detachee_2_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_2_distributeur INTEGER,
    nom_piece_detachee_3_distributeur TEXT,
    delai_jours_piece_detachee_3_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_3_distributeur INTEGER,
    nom_piece_detachee_4_distributeur TEXT,
    delai_jours_piece_detachee_4_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_4_distributeur INTEGER,
    nom_piece_detachee_5_distributeur TEXT,
    delai_jours_piece_detachee_5_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_5_distributeur INTEGER,
    nom_piece_detachee_6_distributeur TEXT,
    delai_jours_piece_detachee_6_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_6_distributeur INTEGER,
    nom_piece_detachee_7_distributeur TEXT,
    delai_jours_piece_detachee_7_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_7_distributeur INTEGER,
    nom_piece_detachee_8_distributeur TEXT,
    delai_jours_piece_detachee_8_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_8_distributeur INTEGER,
    nom_piece_detachee_9_distributeur TEXT,
    delai_jours_piece_detachee_9_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_9_distributeur INTEGER,
    nom_piece_detachee_10_distributeur TEXT,
    delai_jours_piece_detachee_10_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_10_distributeur INTEGER,
    nom_piece_detachee_11_distributeur TEXT,
    delai_jours_piece_detachee_11_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_11_distributeur INTEGER,
    nom_piece_detachee_12_distributeur TEXT,
    delai_jours_piece_detachee_12_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_12_distributeur INTEGER,
    nom_piece_detachee_13_distributeur TEXT,
    delai_jours_piece_detachee_13_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_13_distributeur INTEGER,
    nom_piece_detachee_14_distributeur TEXT,
    delai_jours_piece_detachee_14_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_14_distributeur INTEGER,
    nom_piece_detachee_15_distributeur TEXT,
    delai_jours_piece_detachee_15_distributeur INTEGER,
    nb_annees_disponibilite_piece_detachee_15_distributeur INTEGER,
    
    -- Spare parts for consumer (15 parts)
    nom_piece_detachee_1_consommateur TEXT,
    delai_jours_piece_detachee_1_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_1_consommateur INTEGER,
    nom_piece_detachee_2_consommateur TEXT,
    delai_jours_piece_detachee_2_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_2_consommateur INTEGER,
    nom_piece_detachee_3_consommateur TEXT,
    delai_jours_piece_detachee_3_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_3_consommateur INTEGER,
    nom_piece_detachee_4_consommateur TEXT,
    delai_jours_piece_detachee_4_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_4_consommateur INTEGER,
    nom_piece_detachee_5_consommateur TEXT,
    delai_jours_piece_detachee_5_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_5_consommateur INTEGER,
    nom_piece_detachee_6_consommateur TEXT,
    delai_jours_piece_detachee_6_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_6_consommateur INTEGER,
    nom_piece_detachee_7_consommateur TEXT,
    delai_jours_piece_detachee_7_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_7_consommateur INTEGER,
    nom_piece_detachee_8_consommateur TEXT,
    delai_jours_piece_detachee_8_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_8_consommateur INTEGER,
    nom_piece_detachee_9_consommateur TEXT,
    delai_jours_piece_detachee_9_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_9_consommateur INTEGER,
    nom_piece_detachee_10_consommateur TEXT,
    delai_jours_piece_detachee_10_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_10_consommateur INTEGER,
    nom_piece_detachee_11_consommateur TEXT,
    delai_jours_piece_detachee_11_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_11_consommateur INTEGER,
    nom_piece_detachee_12_consommateur TEXT,
    delai_jours_piece_detachee_12_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_12_consommateur INTEGER,
    nom_piece_detachee_13_consommateur TEXT,
    delai_jours_piece_detachee_13_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_13_consommateur INTEGER,
    nom_piece_detachee_14_consommateur TEXT,
    delai_jours_piece_detachee_14_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_14_consommateur INTEGER,
    nom_piece_detachee_15_consommateur TEXT,
    delai_jours_piece_detachee_15_consommateur INTEGER,
    nb_annees_disponibilite_piece_detachee_15_consommateur INTEGER,
    
    -- Metadata fields (only in consolidated file)
    last_modified TIMESTAMP NULL,
    datagouv_dataset_id TEXT NULL,
    datagouv_resource_id TEXT NULL,
    datagouv_organization_or_owner TEXT NULL,
    is_orga BOOLEAN NULL,
    created_at TIMESTAMP NULL,
    
    -- Timestamps
    created_at_db TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at_db TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for better search performance
CREATE INDEX idx_washing_machines_nom_modele ON washing_machines(nom_modele);
CREATE INDEX idx_washing_machines_nom_metteur_sur_le_marche ON washing_machines(nom_metteur_sur_le_marche);
CREATE INDEX idx_washing_machines_note_reparabilite ON washing_machines(note_reparabilite);
CREATE INDEX idx_washing_machines_note_fiabilite ON washing_machines(note_fiabilite);
CREATE INDEX idx_washing_machines_date_calcul ON washing_machines(date_calcul);
CREATE INDEX idx_washing_machines_id_unique ON washing_machines(id_unique);

-- Create a trigger to update updated_at_db
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at_db = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_washing_machines_updated_at 
    BEFORE UPDATE ON washing_machines 
    FOR EACH ROW 
    EXECUTE FUNCTION update_updated_at_column(); 